// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sentinela.Api.Data;

#nullable disable

namespace Sentinela.Api.Migrations
{
    [DbContext(typeof(SentinelaDbContext))]
    [Migration("20260713190000_AddFontesConfirmacaoECpfProprietario")]
    partial class AddFontesConfirmacaoECpfProprietario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sentinela.Api.Models.Multa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnalisadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnaliseIa")
                        .HasColumnType("text");

                    b.Property<string>("ArtigoCtb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AutuacaoPdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("BoletoPdfUrl")
                        .HasColumnType("text");

                    b.Property<double?>("ChanceRecursoPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("CodigoInfracaoCtb")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ComoEvitarNoFuturo")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataInfracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoInfracao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DetectadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FontesConfirmacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FundamentacaoRecurso")
                        .HasColumnType("text");

                    b.Property<int>("Gravidade")
                        .HasColumnType("integer");

                    b.Property<string>("LocalInfracao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroAutoInfracao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OndeObterDesconto")
                        .HasColumnType("text");

                    b.Property<string>("OndeRecorrer")
                        .HasColumnType("text");

                    b.Property<string>("OrgaoAutuador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PrazoDefesaPrevia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PrazoRecursoCetran")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PrazoRecursoJari")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TextoDefesa")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId", "NumeroAutoInfracao")
                        .IsUnique();

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("Sentinela.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AtividadeRemunerada")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaCnh")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime?>("CnhValidadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExpedicaoCnh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NotificarEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarWhatsApp")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroRegistroCnh")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SituacaoCnh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidadeCnhOficial")
                        .HasColumnType("date");

                    b.Property<string>("WhatsAppNumero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sentinela.Api.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CpfProprietario")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MonitoramentoAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime?>("UltimaVerificacaoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Placa", "Renavam")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Sentinela.Api.Models.Multa", b =>
                {
                    b.HasOne("Sentinela.Api.Models.Veiculo", "Veiculo")
                        .WithMany("Multas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Sentinela.Api.Models.Veiculo", b =>
                {
                    b.HasOne("Sentinela.Api.Models.Usuario", "Usuario")
                        .WithMany("Veiculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sentinela.Api.Models.Usuario", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Sentinela.Api.Models.Veiculo", b =>
                {
                    b.Navigation("Multas");
                });
#pragma warning restore 612, 618
        }
    }
}
